### ISSUE TITLE
Very line oriented

### ISSUE THREAD

**Issue by wallymathieu** [LogFlow/LogFlow#7]
It would nice to pipe xml logs using this tool. For instance log4j or log4net formated file logs.

**Comment by emilcardell** [comment]
You could write your own xml-file input to solve the problem if they are not on the same line. The problem is that you need to read the whole file to "validate" the xml if it's not on the same line.

Do you have an example of the logfiles you want to read?

**Comment by wallymathieu** [comment]
Well, you only need the flushed new chunk to validate. Sample xml and use of position: https://github.com/wallymathieu/log4net-logviewer/blob/master/src/Tests/Log4NetTests.cs

**Comment by wallymathieu** [comment]
It would perhaps be more general to separate "splitting of lines" from "reading the file" and have a splitter or preparser that can turn it into lines?

**Comment by emilcardell** [comment]
The problem is that a lot of performance is connected to how we read the file using the file line positions. We should definitely rename the fileinput to something to do with line. And change the syntax to log entry instead of line.

However I we don't have a demand for this use case but if you build a non line based file reader I'll be happy to put it in the main project.

**Comment by wallymathieu** [comment]
I started looking at something like that but the interface is line oriented as well:

```
public abstract Result GetLine();
```

**Comment by wallymathieu** [comment]
You could perhaps improve performance by reading bigger chunks or by using BufferedStream in the existing implementation.

**Comment by emilcardell** [comment]
I like the idea not to be line oriented. The better name should be GetNextLogEntry()

About performance. If you kan make it work please send a pull request.

**Comment by wallymathieu** [comment]
You could try to wrap the usage of the stream with a:
 BufferedStream
In order to read bigger chunks (the default is 4096 bytes)
I would guess that it would be more performant to read a chunk that somewhat matches the limit * an estimated line size.

**Comment by wallymathieu** [comment]
I don't think you have much of a performance issue ;) Most time will probably be spent on disk io and posting to elastic. But since it's in a service, as long as it's efficient enough, it will probably be okey.
